spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/mp?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: hz
    password: 12345


mybatis-plus:
  #mybatis全局配置文件位置
  #config-location: classpath:mybatis-config.xml
  #mapper映射文件位置
  mapper-locations: classpath*:/mybatis/**/*.xml
  #关联包
#  type-aliases-package: com.java.pojo
  configuration:
    #驼峰命名规则：mp默认开启
    map-underscore-to-camel-case: true
    #二级缓存：mp默认开启
    cache-enabled: true

  #全局配置
  global-config:
    #DB策略配置
    db-config:
      #主键策略
      id-type: auto
      #表的前缀名
      table-prefix: tb_
      # 删除后的字段值(默认是1)
      logic-delete-value: 1
      # 为删除时 的字段值(默认是0)
      logic-not-delete-value: 0
  #扫描自定义枚举包
  type-enums-package: com.java.enums